# docker-compose.yml

version: '3.8'

services:
  # backend:
  #   build: ./backend
  #   volumes:
  #     - ./backend:/usr/src/app
  #   expose:
  #     - 8000
  #   depends_on:
  #     - db

  reverse_proxy:
    build:
      context: ./nginx
      args:
        - ENV=dev
    # volumes:
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:8080
      # depends_on:
      # - backend
      # extra_hosts:
      # - "host.docker.internal:192.168.64.1"
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

  db:
    image: postgres:16.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
