# docker-compose.yml

version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    expose:
      - 8000
    depends_on:
      - db
    environment:
      PROD: 'True'
      DB_HOST: 'db'

  frontend:
    # stdin_open: true
    build: ./frontend
    volumes:
      - frontendshare:/usr/src/app
    # environment:
    #   - NODE_ENV=production
    depends_on:
      - backend

  reverse_proxy:
    build:
      context: ./nginx
      args:
        - ENV=prod
    volumes:
      - frontendshare:/app/static
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:8080
    depends_on:
      - backend
      - frontend

  db:
    image: postgres:16.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  frontendshare:
  db:
