# Author: Alexandr Celakovsky - xcelak00

services:
  backend:
    build: ./backend
    volumes:
      - backendshare:/usr/src/app
    expose:
      - 8000
    depends_on:
      - db
    environment:
      - PROD='True'
      - DB_HOST=db
    # command: tail -F /dev/null

  celerybeat:
    build: ./backend
    command: "/bin/sh -c '/usr/src/app/celerybeat-start.sh'"
    restart: on-failure
    volumes:
        - backendshare:/usr/src/app
    depends_on:
        - backend
        - redis
    environment:
      - PROD='True'
      - DB_HOST=db

  celeryworker:
    build: ./backend
    command: celery -A myproject worker --loglevel=INFO
    volumes:
        - backendshare:/usr/src/app
    depends_on:
        - backend
        - redis
        - celerybeat
    environment:
      - PROD='True'
      - DB_HOST=db

  frontend:
    # stdin_open: true
    build: ./frontend
    volumes:
      - frontendshare:/usr/src/app
    # environment:
    #   - NODE_ENV=production
    depends_on:
      - backend

  reverse_proxy:
    build:
      context: ./nginx
      args:
        - ENV=prod
    volumes:
      - frontendshare:/app/static
      - backendshare:/backend
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
    depends_on:
      - backend
      # - frontend

  db:
    image: postgres:16.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    # ports:
      # - '6379:6379'

volumes:
  frontendshare:
  db:
  backendshare:
