# Generated by Django 4.2.5 on 2024-04-20 18:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flowerbed', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, null=True, unique=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(blank=True, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'discounts',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='created', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discounts', models.ManyToManyField(blank=True, to='orders.discounts')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.profile')),
            ],
            options={
                'db_table': 'orders',
                'db_table_comment': 'There"s flowerbed orders and product_orders',
            },
        ),
        migrations.CreateModel(
            name='ProductOrders',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.order')),
            ],
            options={
                'db_table': 'product_orders',
                'db_table_comment': 'There"s flowerbed orders and product_orders',
            },
            bases=('orders.order',),
        ),
        migrations.CreateModel(
            name='ProductOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('greenhouseName', models.CharField(blank=True, max_length=255, null=True)),
                ('greenhouseId', models.IntegerField(blank=True, null=True)),
                ('productName', models.CharField(blank=True, max_length=255, null=True)),
                ('productImage', models.CharField(blank=True, max_length=255, null=True)),
                ('productId', models.IntegerField(blank=True, null=True)),
                ('productOrder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.productorders')),
            ],
            options={
                'db_table': 'product_order_items',
                'db_table_comment': 'There"s flowerbed orders and product_orders',
            },
        ),
        migrations.CreateModel(
            name='FlowerbedOrders',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.order')),
                ('rent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flowerbed.rent')),
            ],
            options={
                'db_table': 'flowerbed_orders',
                'db_table_comment': 'There"s flowerbed orders and product_orders',
            },
            bases=('orders.order',),
        ),
    ]
