# Generated by Django 4.2.5 on 2024-05-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_discount_remove_order_discounts_delete_discounts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorderitems',
            name='marketplaceProductId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
