# Generated by Django 4.2.5 on 2024-04-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_flowerbedorders_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorderitems',
            name='productId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
