# Generated by Django 4.2.5 on 2024-02-14 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_remove_profile_nickname'),
        ('orders', '0003_remove_flowerbedorders_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowerbedorders',
            name='order_ptr',
        ),
        migrations.RemoveField(
            model_name='productorders',
            name='order_ptr',
        ),
        migrations.AddField(
            model_name='flowerbedorders',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flowerbedorders',
            name='discounts',
            field=models.ManyToManyField(blank=True, to='orders.discounts'),
        ),
        migrations.AddField(
            model_name='flowerbedorders',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='flowerbedorders',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flowerbedorders',
            name='status',
            field=models.CharField(blank=True, default='created', null=True),
        ),
        migrations.AddField(
            model_name='flowerbedorders',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.profile'),
        ),
        migrations.AddField(
            model_name='productorders',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productorders',
            name='discounts',
            field=models.ManyToManyField(blank=True, to='orders.discounts'),
        ),
        migrations.AddField(
            model_name='productorders',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productorders',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productorders',
            name='status',
            field=models.CharField(blank=True, default='created', null=True),
        ),
        migrations.AddField(
            model_name='productorders',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.profile'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
