# Generated by Django 4.2.5 on 2024-02-14 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_remove_profile_nickname'),
        ('orders', '0004_remove_flowerbedorders_order_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowerbedorders',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='flowerbedorders',
            name='discounts',
        ),
        migrations.RemoveField(
            model_name='flowerbedorders',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='flowerbedorders',
            name='id',
        ),
        migrations.RemoveField(
            model_name='flowerbedorders',
            name='status',
        ),
        migrations.RemoveField(
            model_name='flowerbedorders',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productorders',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productorders',
            name='discounts',
        ),
        migrations.RemoveField(
            model_name='productorders',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='productorders',
            name='id',
        ),
        migrations.RemoveField(
            model_name='productorders',
            name='status',
        ),
        migrations.RemoveField(
            model_name='productorders',
            name='user',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='created', null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('discounts', models.ManyToManyField(blank=True, to='orders.discounts')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.profile')),
            ],
            options={
                'db_table': 'orders',
                'db_table_comment': 'There"s flowerbed orders and product_orders',
            },
        ),
        migrations.AddField(
            model_name='flowerbedorders',
            name='order_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productorders',
            name='order_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.order'),
            preserve_default=False,
        ),
    ]
