# Generated by Django 4.2.5 on 2024-02-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_discounts_percentage_alter_discounts_sum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('greenhouseName', models.CharField(blank=True, max_length=255, null=True)),
                ('productName', models.CharField(blank=True, max_length=255, null=True)),
                ('productImage', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'product_order_items',
                'db_table_comment': 'There"s flowerbed orders and product_orders',
            },
        ),
    ]
