# Generated by Django 4.2.5 on 2024-02-25 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_productorderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorderitems',
            name='productOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.productorders'),
        ),
    ]
