# Generated by Django 4.2.5 on 2024-03-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_productorderitems_productorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorderitems',
            name='greenhouseId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
