# Generated by Django 4.2.5 on 2023-12-12 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_profile_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
    ]
