# Generated by Django 4.2.5 on 2024-03-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_remove_profile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='primary_greenhouseId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
