# Generated by Django 4.2.5 on 2024-02-07 14:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quickstart', '0004_remove_profile_nickname'),
        ('flowerbed', '0013_alter_flowerbed_priceperday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, null=True, unique=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(blank=True, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('sum', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'discounts',
            },
        ),
        migrations.CreateModel(
            name='ProductOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='created', null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('discounts', models.ManyToManyField(blank=True, to='ordering.discounts')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.profile')),
            ],
            options={
                'db_table': 'product_orders',
                'db_table_comment': 'There"s flowerbed orders and product_orders',
            },
        ),
        migrations.CreateModel(
            name='FlowerbedOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='created', null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 7, 14, 44, 5, 102551), null=True)),
                ('final_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('discounts', models.ManyToManyField(blank=True, to='ordering.discounts')),
                ('rent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='flowerbed.rent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.profile')),
            ],
            options={
                'db_table': 'flowerbed_orders',
                'db_table_comment': 'There"s flowerbed orders and product_orders',
            },
        ),
    ]
