# Generated by Django 4.2.5 on 2024-02-07 14:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flowerbed', '0013_alter_flowerbed_priceperday'),
        ('ordering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowerbedorders',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flowerbedorders',
            name='rent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='flowerbed.rent'),
        ),
    ]
