# Generated by Django 4.2.5 on 2024-04-15 17:31

from django.db import migrations, models
import newsletter.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=newsletter.models.upload_to),
        ),
    ]
