# Generated by Django 4.2.5 on 2024-04-15 18:10

from django.db import migrations, models
import newsletter.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_alter_newsletterimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterimage',
            name='image_height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newsletterimage',
            name='image_width',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newsletterimage',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to=newsletter.models.upload_to, width_field='image_width'),
        ),
    ]
