# Generated by Django 4.2.5 on 2024-04-04 17:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('greenhouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('greenhouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='greenhouse.greenhouse')),
            ],
            options={
                'db_table': 'work_statements',
            },
        ),
        migrations.CreateModel(
            name='WorkStatementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='submitted', null=True)),
                ('title', models.CharField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('hours', models.IntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='author', to='users.profile')),
                ('work_statement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='greenhouse.workstatement')),
            ],
            options={
                'db_table': 'work_statement_items',
            },
        ),
    ]
