# Generated by Django 4.2.5 on 2024-05-08 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenhousePlantEmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2grams_per_piece', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('plant_names', models.CharField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('greenhouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='greenhouse.greenhouse')),
            ],
            options={
                'db_table': 'greenhouse_plant_emissions',
            },
        ),
    ]
