# Generated by Django 4.2.5 on 2024-01-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenhouseaddress',
            name='city',
            field=models.CharField(blank=True, default='Brno', null=True),
        ),
        migrations.AlterField(
            model_name='greenhouseaddress',
            name='country',
            field=models.CharField(blank=True, default='CZ', null=True),
        ),
    ]
