# Generated by Django 4.2.5 on 2024-02-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0002_alter_greenhouseaddress_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenhouse',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
