# Generated by Django 4.2.5 on 2024-04-04 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('greenhouse', '0002_workstatement_workstatementitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workstatementitem',
            name='author',
        ),
        migrations.RemoveField(
            model_name='workstatementitem',
            name='status',
        ),
        migrations.AddField(
            model_name='workstatement',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='author', to='users.profile'),
        ),
        migrations.AddField(
            model_name='workstatement',
            name='status',
            field=models.CharField(blank=True, default='submitted', null=True),
        ),
    ]
