# Generated by Django 4.2.5 on 2024-02-02 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_remove_profile_nickname'),
        ('greenhouse', '0003_alter_greenhouse_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhouse',
            name='caretaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='caretaker', to='quickstart.profile'),
        ),
        migrations.AlterField(
            model_name='greenhouse',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to='quickstart.profile'),
            preserve_default=False,
        ),
    ]
