# Generated by Django 4.2.5 on 2024-02-05 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0004_greenhouse_caretaker_alter_greenhouse_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenhouseBusinessHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('greenhouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='greenhouse.greenhouse')),
            ],
            options={
                'db_table': 'greenhouse_business_hours',
            },
        ),
        migrations.CreateModel(
            name='GreenhouseBusinessHourPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.TimeField()),
                ('close', models.TimeField()),
                ('business_hour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='greenhouse.greenhousebusinesshour')),
            ],
            options={
                'db_table': 'greenhouse_business_hour_periods',
            },
        ),
    ]
