# Generated by Django 4.2.5 on 2024-04-07 12:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('greenhouse', '0004_alter_greenhouse_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='submitted', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='author', to='users.profile')),
                ('greenhouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='greenhouse.greenhouse')),
            ],
            options={
                'db_table': 'timesheets',
            },
        ),
        migrations.CreateModel(
            name='TimesheetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('hours', models.IntegerField(blank=True, null=True)),
                ('timesheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='greenhouse.timesheet')),
            ],
            options={
                'db_table': 'timesheet_items',
            },
        ),
        migrations.RemoveField(
            model_name='workstatementitem',
            name='work_statement',
        ),
        migrations.DeleteModel(
            name='WorkStatement',
        ),
        migrations.DeleteModel(
            name='WorkStatementItem',
        ),
    ]
