# Generated by Django 4.2.5 on 2024-02-05 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0005_greenhousebusinesshour_greenhousebusinesshourperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenhousebusinesshour',
            name='greenhouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='greenhouse.greenhouse'),
        ),
        migrations.AlterField(
            model_name='greenhousebusinesshourperiod',
            name='business_hour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='greenhouse.greenhousebusinesshour'),
        ),
    ]
