# Generated by Django 4.2.5 on 2024-04-08 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('greenhouse', '0006_timesheetupdate_remove_timesheetitem_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetupdate',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='update_author', to='users.profile'),
        ),
        migrations.AddField(
            model_name='timesheetupdate',
            name='status',
            field=models.CharField(blank=True, default='submitted', null=True),
        ),
    ]
