# Generated by Django 4.2.5 on 2024-04-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0007_timesheetupdate_author_timesheetupdate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
