# Generated by Django 4.2.5 on 2024-04-16 18:58

from django.db import migrations, models
import greenhouse.models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0008_timesheet_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhouse',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to=greenhouse.models.greenhouse_upload_to, width_field='image_width'),
        ),
        migrations.AddField(
            model_name='greenhouse',
            name='image_height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='greenhouse',
            name='image_width',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
