# Generated by Django 4.2.5 on 2024-01-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flowerbed',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, null=True)),
                ('disabled', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'flowerbeds',
            },
        ),
    ]
