# Generated by Django 4.2.5 on 2024-04-20 18:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('greenhouse', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flowerbed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True)),
                ('disabled', models.BooleanField(blank=True, default=False, null=True)),
                ('dimension_width', models.FloatField(default=1.0)),
                ('dimension_height', models.FloatField(default=1.0)),
                ('idealPlants', models.CharField(blank=True, max_length=100, null=True)),
                ('tools', models.CharField(blank=True, max_length=100, null=True)),
                ('pricePerDay', models.DecimalField(decimal_places=5, default=50, max_digits=10)),
                ('greenhouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='greenhouse.greenhouse')),
            ],
            options={
                'db_table': 'flowerbeds',
            },
        ),
        migrations.CreateModel(
            name='UserFlowerbed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flowerbed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flowerbed.flowerbed')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
            ],
            options={
                'db_table': 'user_flowerbeds',
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rented_from', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('rented_to', models.DateTimeField(blank=True, null=True)),
                ('flowerbed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='flowerbed.flowerbed')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.profile')),
            ],
            options={
                'db_table': 'rents',
            },
        ),
        migrations.CreateModel(
            name='FlowerbedNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('user_flowerbed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flowerbed.userflowerbed')),
            ],
            options={
                'db_table': 'flowerbed_notes',
            },
        ),
        migrations.CreateModel(
            name='FlowerbedHarvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('user_flowerbed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flowerbed.userflowerbed')),
            ],
            options={
                'db_table': 'flowerbed_harvests',
            },
        ),
    ]
