# Generated by Django 4.2.5 on 2024-04-18 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_activated_once'),
        ('flowerbed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFlowerbed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flowerbed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flowerbed.flowerbed')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
            ],
            options={
                'db_table': 'user_flowerbeds',
            },
        ),
        migrations.CreateModel(
            name='FlowerbedNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('user_flowerbed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flowerbed.userflowerbed')),
            ],
            options={
                'db_table': 'flowerbed_notes',
            },
        ),
        migrations.CreateModel(
            name='FlowerbedHarvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('user_flowerbed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flowerbed.userflowerbed')),
            ],
            options={
                'db_table': 'flowerbed_harvests',
            },
        ),
    ]
