# Generated by Django 4.2.5 on 2024-01-05 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('greenhouse', '0001_initial'),
        ('flowerbed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowerbed',
            name='greenhouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='greenhouse.greenhouse'),
        ),
    ]
