# Generated by Django 4.2.5 on 2024-01-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerbed', '0003_alter_flowerbed_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowerbed',
            name='disabled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
