# Generated by Django 4.2.5 on 2024-01-05 23:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowerbed', '0004_alter_flowerbed_disabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leases',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('leased_from', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('leased_to', models.DateTimeField(blank=True, null=True)),
                ('flowerbed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='flowerbed.flowerbed')),
            ],
            options={
                'db_table': 'leases',
            },
        ),
    ]
