# Generated by Django 4.2.5 on 2024-01-05 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowerbed', '0005_leases'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leases',
            new_name='Lease',
        ),
    ]
