# Generated by Django 4.2.5 on 2024-01-05 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_remove_profile_nickname'),
        ('flowerbed', '0006_rename_leases_lease'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.profile'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
