# Generated by Django 4.2.5 on 2024-02-02 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowerbed', '0008_flowerbed_dimension_height_flowerbed_dimension_width_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flowerbedidealplants',
            old_name='plant',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='flowerbedtools',
            old_name='tool',
            new_name='name',
        ),
    ]
