# Generated by Django 4.2.5 on 2024-02-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerbed', '0009_rename_plant_flowerbedidealplants_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowerbedtools',
            name='flowerbed',
        ),
        migrations.AddField(
            model_name='flowerbed',
            name='idealPlants',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flowerbed',
            name='tools',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='FlowerbedIdealPlants',
        ),
        migrations.DeleteModel(
            name='FlowerbedTools',
        ),
    ]
