# Generated by Django 4.2.5 on 2024-02-07 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_remove_profile_nickname'),
        ('flowerbed', '0010_remove_flowerbedtools_flowerbed_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lease',
            new_name='Rent',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='leased_from',
            new_name='rented_from',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='leased_to',
            new_name='rented_to',
        ),
        migrations.AlterModelTable(
            name='rent',
            table='rents',
        ),
    ]
