# Generated by Django 4.2.5 on 2024-02-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerbed', '0011_rename_lease_rent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowerbed',
            name='pricePerDay',
            field=models.FloatField(default=50),
        ),
    ]
