# Generated by Django 4.2.5 on 2024-02-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerbed', '0012_flowerbed_priceperday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowerbed',
            name='pricePerDay',
            field=models.DecimalField(decimal_places=5, default=50, max_digits=10),
        ),
    ]
