# Generated by Django 4.2.5 on 2024-04-14 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_unsubscribe_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='unsubscribe_token',
        ),
    ]
