# Generated by Django 4.2.5 on 2024-04-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profile_unsubscribe_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activated_once',
            field=models.BooleanField(default=False),
        ),
    ]
